import fs from 'node:fs/promises';
import path from 'node:path';
import {parseEpsisSmp} from './epsis-source.mjs';
import {parseNuclear} from './nuclear-source.mjs';
import {environmentalJobs} from './environmental-source.mjs';
import {catalog} from './catalog.mjs';
import {mergeRows,mutate,today,ROOT} from './store.mjs';
import {pathToFileURL} from 'node:url';
const clean=s=>s.replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/\s+/g,' ').trim();
export const tables=html=>[...html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)].map(m=>[...m[1].matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(c=>clean(c[1])));
const num=s=>Number(s.replaceAll(',','').trim());
async function fetchText(url){const r=await fetch(url,{signal:AbortSignal.timeout(25000),headers:{'User-Agent':'UtilityMacroLocal/1.0'}});if(!r.ok)throw Error('HTTP '+r.status);return r.text();}
export function parseFred(text,id,code){const lines=text.trim().split(/\r?\n/);if(lines.shift()!==`observation_date,${code}`)throw Error('FRED 열 형식 변경');const rows=[];for(const line of lines){const [date,v]=line.split(',');if(!v||v==='.')continue;if(!Number.isFinite(Number(v)))throw Error('FRED 숫자 오류');rows.push({id,date,value:Number(v),source:'FRED · '+code,url:'https://fred.stlouisfed.org/series/'+code});}if(rows.length<2)throw Error('FRED 관측값 부족');return rows;}
export function parseSmp(html){const rows=tables(html),out=[];let region='';for(const row of rows){if(row[0]?.includes('육지'))region='육지';else if(row[0]?.includes('제주'))region='제주';else if(row[0]?.includes('통합'))region='통합';if(region!=='육지')continue;const idx=row.findIndex(x=>/^\d{2,4}년$/.test(x));if(idx<0)continue;let yr=parseInt(row[idx]);if(yr<100)yr+=2000;row.slice(idx+1).forEach((v,i)=>{if(!v||!Number.isFinite(num(v))||i>11)return;const date=`${yr}-${String(i+1).padStart(2,'0')}-01`;if(date<=today())out.push({id:'smp',date,value:num(v),source:'KPX · 육지 월평균',url:'https://new.kpx.or.kr/smpMonthly.es?mid=a10404080300'});});}if(!out.length)throw Error('SMP 표 구조 또는 데이터 확인 필요');return out;}
export function parseKogas(html){const rows=tables(html);const dateRow=rows.find(r=>r.some(c=>c.includes('시행일')));const dm=dateRow?.join(' ').match(/(20\d{2})\s*\.\s*(\d{1,2})\s*\.\s*(\d{1,2})/);const r=rows.find(r=>r[0]==='합계');if(!dm||!r||r.length<3||!clean(html).includes('원/GJ'))throw Error('가스요금 표 구조 확인 필요');const date=`${dm[1]}-${dm[2].padStart(2,'0')}-${dm[3].padStart(2,'0')}`;return ['gas_power','gas_chp'].map((id,i)=>({id,date,value:num(r[i+1]),source:'한국가스공사 · 발전용 공시요금',url:'https://www.kogas.or.kr/site/koGas/1040402000000'}));}
export function parseDemand(html){const out=[];for(const r of tables(html)){const idx=r.findIndex(v=>/^20\d{2}[.-]\d{2}[.-]\d{2}$/.test(v));if(idx<0)continue;const date=r[idx].replaceAll('.','-');const peak=num(r[idx+4]),reserve=num(r.at(-1));if(!Number.isFinite(peak)||peak<10000||peak>200000||!Number.isFinite(reserve)||reserve<0||reserve>200)throw Error('전력수급 표 열 검증 실패');for(const [id,value] of [['peak',peak],['reserve',reserve]])out.push({id,date,value,source:'KPX · 전력수급실적',url:'https://new.kpx.or.kr/powerDemandPerform.es?mid=a10404060000'});}if(!out.length)throw Error('전력수급 표 구조 확인 필요');return out;}
export function parseReceivable(html){const rows=tables(html),idx=rows.findIndex(r=>r[0]?.replace(/\s/g,'')==='누적미수금');if(idx<1)throw Error('미수금 표 구조 확인 필요');const years=rows[idx-1].slice(1).map(x=>x.match(/(\d{2,4})년/)?.[1]);const values=rows[idx].slice(1);if(years.length!==values.length||years.some(y=>!y)||values.some(v=>!v.trim()||!Number.isFinite(num(v))))throw Error('미수금 연도/값 검증 실패');return years.map((y,i)=>({id:'receivable',date:`${Number(y)<100?2000+Number(y):Number(y)}-12-31`,value:num(values[i]),source:'한국가스공사 · 민수용 연말 미수금',url:'https://www.kogas.or.kr/site/koGas/1040403010000'})).filter(r=>r.date<=today());}
export function parseYahoo(j,id,source,url,{includeToday=false}={}){const r=j?.chart?.result?.[0];if(!r||!Array.isArray(r.timestamp))throw Error('Yahoo 차트 형식 변경');const close=r.indicators?.quote?.[0]?.close||[];const out=[];for(let i=0;i<r.timestamp.length;i++){const v=close[i];if(v==null||!Number.isFinite(v)||v<=0)continue;const date=new Date(r.timestamp[i]*1000).toISOString().slice(0,10);if(date>today()||(date===today()&&!includeToday))continue;out.push({id,date,value:v,source,url});}if(!out.length)throw Error('Yahoo 종가 없음');return out;}
export function parseWci(html){const m=html.match(/World Container Index \(WCI\)\s+(?:increased|decreased|remained|rose|fell|was)[^$]{0,60}\$([\d,]+)\s+per 40ft/i);const d=html.match(/assessment for \w+day,\s*(\d{1,2}) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\w* (20\d{2})/i);if(!m||!d)throw Error('Drewry WCI 문구 변경');const mon={Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8,Sep:9,Oct:10,Nov:11,Dec:12}[d[2].slice(0,3)];const value=num(m[1]);if(!(value>500&&value<30000))throw Error('WCI 값 범위 이상');return [{id:'wci',date:`${d[3]}-${String(mon).padStart(2,'0')}-${d[1].padStart(2,'0')}`,value,source:'Drewry · WCI 종합',url:'https://www.drewry.co.uk/supply-chain-advisors/supply-chain-expertise/world-container-index-assessed-by-drewry'}];}
const browserUA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36';
export function parseDatawrapperScfi(csv){const lines=csv.trim().split(/\r?\n/);if(lines.shift()?.trim()!=='Date,SCFI')throw Error('SCFI CSV 열 형식 변경');const out=[];for(const l of lines){const [d,v]=l.split(',');if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Number(v)))continue;const value=Number(v);if(value<200||value>10000)throw Error('SCFI 값 범위 이상');out.push({id:'scfi',date:d,value,source:'Opencontainer · Datawrapper(SSE 재게시)',url:'https://opencontainer.kr/index/scfi-overall/'});}if(out.length<100)throw Error('SCFI 이력 부족');return out;}
const idMonth={jan:1,feb:2,mar:3,apr:4,mei:5,may:5,jun:6,jul:7,agt:8,agu:8,aug:8,sep:9,okt:10,oct:10,nov:11,des:12,dec:12};
const idNum=s=>{const m=String(s).match(/([\d.]+,\d+|\d[\d.]*)/);if(!m)return NaN;return Number(m[1].replace(/\./g,'').replace(',','.'));};
export function parseGimniHr(html){const url='https://gimni.org/harga-cpo';const out=[];for(const r of tables(html)){const d=r[0]?.match(/^(\d{1,2}) (\w{3})\w* (20\d{2})$/);if(!d||r.length<4)continue;const mon=idMonth[d[2].toLowerCase()];if(!mon)continue;const date=`${d[3]}-${String(mon).padStart(2,'0')}-01`;const hr=idNum(r[1]);const bk=Number((r[2].match(/US\$\s*([\d.,]+)\s*\/MT/)||[])[1]?.replace(/\./g,'').replace(',','.'));const pct=idNum(r[3]);if(!(hr>300&&hr<3000)||!Number.isFinite(bk)||!(pct>=0&&pct<=30))throw Error('GIMNI HR 표 해석 실패: '+r.slice(0,4).join('|'));out.push({id:'cpo_hr',date,value:hr,source:'GIMNI · Kemendag HR',url},{id:'cpo_duty',date,value:Math.round((bk+hr*pct/100)*100)/100,source:'GIMNI · Bea Keluar + Pungutan',url});}if(out.length<4)throw Error('GIMNI HR 행 없음');return out;}
async function fetchScfi(){const statePath=path.join(ROOT,'data','scfi-datawrapper.json');let state={version:1};try{state=JSON.parse(await fs.readFile(statePath,'utf8'));}catch{}let v=Math.max(1,state.version||1),best=null;for(let i=0;i<150;i++){const r=await fetch(`https://datawrapper.dwcdn.net/xlvuj/${v}/dataset.csv`,{signal:AbortSignal.timeout(20000),headers:{'User-Agent':browserUA}});if(r.status===404)break;if(!r.ok)throw Error('Datawrapper HTTP '+r.status);best={version:v,csv:await r.text()};v++;}if(!best)throw Error('Datawrapper SCFI 버전 없음');const rows=parseDatawrapperScfi(best.csv);await fs.writeFile(statePath,JSON.stringify({version:best.version,last:rows.at(-1).date,checkedAt:new Date().toISOString()}));return rows;}
const MONTH_CODES='FGHJKMNQUVXZ';
const monthsBetween=(a,b)=>(Number(b.slice(0,4))-Number(a.slice(0,4)))*12+Number(b.slice(5,7))-Number(a.slice(5,7));
async function fetchOilCurve(){const now=new Date();const out=[];const snap={asOf:new Date().toISOString(),wti:[],brent:[]};
 for(const [root,key,id,label] of [['CL','wti','wti_m12','NYMEX WTI'],['BZ','brent','brent_m12','ICE Brent']]){
  for(let k=1;k<=15;k++){const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+k,1));const sym=`${root}${MONTH_CODES[d.getUTCMonth()]}${String(d.getUTCFullYear()).slice(2)}.NYM`;
   const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${sym}?range=5d&interval=1d`,{signal:AbortSignal.timeout(20000),headers:{'User-Agent':browserUA}});
   if(r.status===404)continue;if(!r.ok)throw Error(sym+' HTTP '+r.status);const m=(await r.json())?.chart?.result?.[0]?.meta;const p=m?.regularMarketPrice;if(!(p>0))continue;
   snap[key].push({contract:d.toISOString().slice(0,7),symbol:sym,price:p,at:new Date(m.regularMarketTime*1000).toISOString()});}
  const c=snap[key];if(c.length<6)throw Error(root+' 월물 확보 부족: '+c.length);
  const front=c[0];const target=c.find(x=>monthsBetween(front.contract,x.contract)===12)||c.at(-1);
  out.push({id,date:today(),value:target.price,source:`Yahoo Finance · ${label} ${target.contract} 월물`,url:'https://finance.yahoo.com/quote/'+target.symbol+'/'});}
 await fs.writeFile(path.join(ROOT,'data','oil-curve.json'),JSON.stringify(snap,null,1));return out;}
import {spawn} from 'node:child_process';
export function parseIci(json,date){const rows=json?.rows||{};const v=Number(rows['4200']);if(!Number.isFinite(v))throw Error('ICI GAR 4200 행 없음');if(v<20||v>250)throw Error('ICI GAR 4200 값 범위 이상: '+v);const a=Number(rows['4300']),b=Number(rows['4100']);if(Number.isFinite(a)&&Number.isFinite(b)&&!(a>=v&&v>=b))throw Error('ICI 인접 행 순서 불일치');const d=date||json.date;if(!/^\d{4}-\d{2}-\d{2}$/.test(d||''))throw Error('ICI 날짜 없음');return [{id:'ici4',date:d,value:v,source:'coaltradeindo.com · 주간 FOB 표(OCR)',url:'https://coaltradeindo.com/ici-coal-price/'}];}
function runPython(args){const py=process.env.UTILITY_ANALYSIS_PYTHON||(process.platform==='win32'?'py':'python3');return new Promise((res,rej)=>{const p=spawn(py,args,{env:{...process.env,PYTHONUTF8:'1'},windowsHide:true});let out='',err='';p.stdout.on('data',c=>out+=c);p.stderr.on('data',c=>err+=c);p.on('error',rej);p.on('close',code=>code===0?res(out):rej(Error('python 종료 '+code+': '+err.slice(-300))));});}
async function fetchIci(){const res=await fetch('https://coaltradeindo.com/ici-coal-price/',{signal:AbortSignal.timeout(30000),headers:{'User-Agent':browserUA,'Accept':'text/html,application/xhtml+xml','Accept-Language':'en-US,en;q=0.9'}});const page=await res.text();const m=page.match(/https?:\/\/[^"' ]*Coal-Price-updated-(\d{1,2})-([A-Za-z]+)-(20\d{2})[^"' ]*\.jpg/i);if(!m)throw Error(`ICI 가격표 이미지 링크 없음 (HTTP ${res.status}, ${page.length}자, title=${(page.match(/<title>([^<]{0,80})/i)||[])[1]||'-'})`);const mon={january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12}[m[2].toLowerCase()];if(!mon)throw Error('ICI 이미지 월 해석 실패: '+m[2]);const date=`${m[3]}-${String(mon).padStart(2,'0')}-${m[1].padStart(2,'0')}`;const img=await fetch(m[0],{signal:AbortSignal.timeout(30000),headers:{'User-Agent':browserUA}});if(!img.ok)throw Error('ICI 이미지 HTTP '+img.status);const dir=path.join(ROOT,'data','ici');await fs.mkdir(dir,{recursive:true});const file=path.join(dir,`ici-${date}.jpg`);await fs.writeFile(file,Buffer.from(await img.arrayBuffer()));const out=await runPython([path.join(ROOT,'ici_ocr.py'),file]);const json=JSON.parse(out.trim().split('\n').at(-1));await fs.writeFile(path.join(dir,`ici-${date}.json`),JSON.stringify(json));return parseIci(json,date);}
export const PROPANE_MMBTU_PER_T=47.7;
export const DERIVED=[{id:'jkm_fei',a:'jkm_futures',b:'fei',k:1/PROPANE_MMBTU_PER_T,source:'자체 산출 · JKMc1 − A7E/47.7',url:'https://finance.yahoo.com/quote/A7E%3DF/'},{id:'jkm_hh',a:'jkm_futures',b:'hh_ng1',k:1,source:'자체 산출 · JKMc1 − NG1',url:'https://finance.yahoo.com/quote/NG%3DF/'}];
export function deriveSpread(db,defs=DERIVED){const rows=[];for(const d of defs){const A=db.series[d.a]||[],B=db.series[d.b]||[];if(!A.length||!B.length)continue;const as=A.at(-1).source,bs=B.at(-1).source;const am=new Map(A.filter(r=>r.source===as).map(r=>[r.date,r.value]));for(const r of B){if(r.source!==bs||!am.has(r.date))continue;rows.push({id:d.id,date:r.date,value:Math.round((am.get(r.date)-r.value*d.k)*100)/100,source:d.source,url:d.url});}}return rows;}
export async function refresh(){const jobs=catalog.filter(x=>x.fred).map(x=>({name:'FRED '+x.fred,ids:[x.id],run:async()=>parseFred(await fetchText(`https://fred.stlouisfed.org/graph/fredgraph.csv?id=${x.fred}&cosd=1900-01-01`),x.id,x.fred)}));
 jobs.push({name:'KPX 장기 SMP',ids:['smp'],run:async()=>parseEpsisSmp(await fetchText('https://epsis.kpx.or.kr/epsisnew/selectEkmaSmpSmpChart.do?menuId=040201'))});
 jobs.push({name:'한수원 연간 이용률',ids:['nuclear'],run:async()=>parseNuclear(await fetchText('https://npp.khnp.co.kr/ON004004002001003'))});
 jobs.push({name:'KOGAS 연말 미수금',ids:['receivable'],run:async()=>parseReceivable(await fetchText('https://www.kogas.or.kr/site/koGas/1040403010000'))});
 jobs.push({name:'KPX SMP',ids:['smp'],run:async()=>parseSmp(await fetchText('https://new.kpx.or.kr/smpMonthly.es?mid=a10404080300'))},{name:'KOGAS 요금',ids:['gas_power','gas_chp'],run:async()=>parseKogas(await fetchText('https://www.kogas.or.kr/site/koGas/1040402000000'))},{name:'KPX 수요',ids:['peak','reserve'],run:async()=>parseDemand(await fetchText('https://new.kpx.or.kr/powerDemandPerform.es?mid=a10404060000'))},
 {name:'서울 기온 재분석',ids:['temperature'],run:async()=>{const end=new Date(Date.now()-6*86400000).toISOString().slice(0,10);const start=new Date(Date.now()-3653*86400000).toISOString().slice(0,10);const url=`https://archive-api.open-meteo.com/v1/archive?latitude=37.5665&longitude=126.9780&start_date=${start}&end_date=${end}&daily=temperature_2m_mean&timezone=Asia%2FSeoul`;const j=JSON.parse(await fetchText(url));if(!j.daily?.time?.length)throw Error('기온 응답 형식 오류');return j.daily.time.flatMap((date,i)=>j.daily.temperature_2m_mean[i]===null?[]:[{id:'temperature',date,value:j.daily.temperature_2m_mean[i],source:'Open-Meteo · ERA5 재분석',url:'https://open-meteo.com/en/docs/historical-weather-api'}]);}});
 for(const [sym,id,label] of [['CL%3DF','wti_cl1','NYMEX CL1'],['BZ%3DF','brent_b1','ICE B1']])jobs.push({name:'Yahoo '+decodeURIComponent(sym),ids:[id],run:async()=>{const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${sym}?period1=946684800&period2=${Math.floor(Date.now()/1000)+86400}&interval=1d`,{signal:AbortSignal.timeout(25000),headers:{'User-Agent':browserUA}});if(!r.ok)throw Error('HTTP '+r.status);return parseYahoo(await r.json(),id,'Yahoo Finance · '+label+' 종가(당일 장중 포함)','https://finance.yahoo.com/quote/'+sym+'/',{includeToday:true});}});
 jobs.push({name:'Yahoo 유가 선물 커브',ids:['wti_m12','brent_m12'],run:fetchOilCurve});
 jobs.push({name:'Coaltradeindo ICI GAR4200',ids:['ici4'],run:fetchIci});
 jobs.push({name:'Yahoo NG=F',ids:['hh_ng1'],run:async()=>{const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/NG%3DF?period1=946684800&period2=${Math.floor(Date.now()/1000)+86400}&interval=1d`,{signal:AbortSignal.timeout(25000),headers:{'User-Agent':browserUA}});if(!r.ok)throw Error('HTTP '+r.status);return parseYahoo(await r.json(),'hh_ng1','Yahoo Finance · NYMEX NG1 종가(당일 장중 포함)','https://finance.yahoo.com/quote/NG%3DF/',{includeToday:true});}});
 jobs.push({name:'Yahoo A7E=F',ids:['fei'],run:async()=>{const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/A7E%3DF?period1=946684800&period2=${Math.floor(Date.now()/1000)+86400}&interval=1d`,{signal:AbortSignal.timeout(25000),headers:{'User-Agent':browserUA}});if(!r.ok)throw Error('HTTP '+r.status);return parseYahoo(await r.json(),'fei','Yahoo Finance · CME Argus 프로판 FEI 연속(A7E=F) 종가','https://finance.yahoo.com/quote/A7E%3DF/');}});
 jobs.push({name:'Yahoo CPO=F',ids:['cpo'],run:async()=>{const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/CPO%3DF?period1=1262304000&period2=${Math.floor(Date.now()/1000)}&interval=1d`,{signal:AbortSignal.timeout(25000),headers:{'User-Agent':browserUA}});if(!r.ok)throw Error('HTTP '+r.status);return parseYahoo(await r.json(),'cpo','Yahoo Finance · CME CPO=F 종가','https://finance.yahoo.com/quote/CPO%3DF/');}});
 jobs.push({name:'Drewry WCI',ids:['wci'],run:async()=>{const r=await fetch('https://www.drewry.co.uk/supply-chain-advisors/supply-chain-expertise/world-container-index-assessed-by-drewry',{signal:AbortSignal.timeout(25000),headers:{'User-Agent':browserUA,'Accept':'text/html'}});if(!r.ok)throw Error('HTTP '+r.status);return parseWci(await r.text());}});
 jobs.push({name:'SCFI Datawrapper',ids:['scfi'],run:fetchScfi});
 jobs.push({name:'GIMNI 인니 CPO HR',ids:['cpo_hr','cpo_duty'],run:async()=>{const r=await fetch('https://gimni.org/harga-cpo',{signal:AbortSignal.timeout(25000),headers:{'User-Agent':browserUA}});if(!r.ok)throw Error('HTTP '+r.status);return parseGimniHr(await r.text());}});
 jobs.push(...environmentalJobs);
 const results=await Promise.all(jobs.map(async job=>{try{const rows=await job.run();return {name:job.name,ids:job.ids,ok:true,count:rows.length,rows};}catch(e){return {name:job.name,ids:job.ids,ok:false,error:e.message};}}));
 await mutate(db=>{for(const r of results)if(r.ok){try{mergeRows(db,r.rows);}catch(e){r.ok=false;r.error=e.message;}}try{const d=deriveSpread(db);mergeRows(db,d);results.push({name:'파생 스프레드(JKM−FEI, JKM−HH)',ids:['jkm_fei','jkm_hh'],ok:true,count:d.length,rows:[]});}catch(e){results.push({name:'파생 스프레드(JKM−FEI, JKM−HH)',ids:['jkm_fei','jkm_hh'],ok:false,error:e.message,rows:[]});}db.runs.push({at:new Date().toISOString(),results:results.map(({rows,...r})=>r)});db.runs=db.runs.slice(-90);});return results.map(({rows,...r})=>r);
}
if(process.argv[1]&&pathToFileURL(process.argv[1]).href===import.meta.url){console.log(JSON.stringify(await refresh(),null,2));}
