import fs from 'node:fs/promises';import {ROOT,today} from './store.mjs';import path from 'node:path';
export const KAU_VINTAGE='KAU26', KAU_CODE='KRD050042609';
export const REC_URL='https://www.kpx.or.kr/recToday.es?mid=a30401000000&device=mbl';
export const KAU_URL='https://ets.krx.co.kr/contents/ETS/03/03010000/ETS03010000.jsp';
const clean=s=>s.replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
const number=s=>{if(s==null||String(s).trim()==='')throw Error('빈 환경상품 가격');const n=Number(String(s).replaceAll(',',''));if(!Number.isFinite(n))throw Error('환경상품 숫자 형식 오류');return n;};
export function parseRec(html){const pairs=[...html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)].map(m=>[...m[1].matchAll(/<t[hd]\b[^>]*>([\s\S]*?)<\/t[hd]>/gi)].map(x=>clean(x[1])));const get=k=>pairs.find(r=>r[0]===k)?.[1];const match=get('거래일')?.match(/(20\d{2})\.(\d{2})\.(\d{2})/);if(!match)throw Error('REC 거래일 표 구조 변경');const date=match.slice(1).join('-'),value=number(get('평균가'));if(value<=0||number(get('거래량'))<=0)throw Error('REC 체결가격 없음');return [{id:'rec',date,value,source:'KPX · REC 현물 거래일 평균가',url:REC_URL}];}
export function parseKau(j){if(!Array.isArray(j.DS1)||!j.DS1.length)throw Error('KRX KAU 일별 자료 없음');if(j.DS1.some(r=>r.isu_eng_abbrv!==KAU_VINTAGE))throw Error('KAU 이행연도 혼합 거부');return j.DS1.filter(r=>r.trd_dd<today()&&number(r.acc_trdvol)>0&&number(r.tdd_clsprc)>0).map(r=>({id:'kau',date:r.trd_dd,value:number(r.tdd_clsprc),source:'KRX · KAU26 거래일 종가',url:KAU_URL}));}
async function request(url,options={}){const r=await fetch(url,{...options,signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('환경상품 HTTP '+r.status);return r.text();}
export async function fetchRec(){const h=await request(REC_URL),rows=parseRec(h);await fs.writeFile(path.join(ROOT,'data','rec-latest-source.html'),h);return rows;}
export async function fetchKau(){const end=new Date(Date.parse(today()+'T00:00:00Z')-86400000).toISOString().slice(0,10).replaceAll('-','');const token=await request('https://ets.krx.co.kr/contents/COM/GenerateOTP.jspx?'+new URLSearchParams({name:'grid',bld:'ETS/03/03010000/ets03010000_05'}));if(!token.trim()||token.includes('<html'))throw Error('KRX 공개 조회 응답 변경');const text=await request('https://ets.krx.co.kr/contents/ETS/99/ETS99000001.jspx',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code:token,isu_cd:KAU_CODE,fromdate:'20260101',todate:end})});const j=JSON.parse(text),rows=parseKau(j);if(!rows.length)throw Error('KAU26 유효 체결 없음');await fs.writeFile(path.join(ROOT,'data','kau26-raw.json'),JSON.stringify(j));return rows;}
export const environmentalJobs=[{name:'KPX REC 현물 평균가',ids:['rec'],run:fetchRec},{name:'KRX KAU26 종가',ids:['kau'],run:fetchKau}];
